### PR TITLE
WIP: Still under construction

### PR DESCRIPTION
**Pull request by day0hero**
The following changes have been implemented in the devsecops pattern. 
- Updated common to implement changes that allow for cluster version flexibility, and using the validated-patterns operator by default.
- Updated advanced-cluster-manager subscription to `release 2.6`
- Moved devsecops resources (nexus, sonarqube, reports-repo) into helm charts and created applications for each that get deployed to the `development` cluster. 
- Aligned devsecops base pattern with multicloud-gitops for consistency in resource declaration.
- Created external secret for htpasswd configuration in reports repo. To distribute the secret to spoke clusters we added a policy, placementrule, and placement binding.
- Created buildconfigs, imagestreams, and applications for cosign rekor and roxctl. 
- All source code repositories for spring-clinic, spring-clinic-gatling have been moved to `hybrid-cloud-demos`
- All container images have been moved from personal repositories to `quay.io/hybridcloudpatterns` - Images like git, and openshift-client have been changed to use imagestreams in the cluster that provide the same service (cli and tools) 
- <gitrepo>/values-secret.yaml.template has been updated with the appropriate secrets template.
- Added argo-rollouts helm chart and application
- Removed config-demo application
- Removed chat-client applications, pipelines and tasks.

### CODE REVIEW

**Comment by beekhof** [comment]
It is worth remembering, that the bigger a PR gets, the harder it is to review.

**Comment by beekhof** [comment]
What's all the new code in ansible/ for?

**Comment by ipbabble** [comment]
LGTM. Check with others.
There are a couple of things we can polish up later but I'd merge this as soon as possible. 
E.g. templating around the registry stuff for things like sonarqube and others.
rm the archive dir.

**Comment by mbaldessari** [comment]
I fixed up most of the CI issues. The current error is a valid one though and prolly needs fixing:
[ERROR] templates/: template: cosign/templates/cosign_pubkey-job.yaml:19:89: executing "cosign/templates/cosign_pubkey-job.yaml" at <.Values.global.xraylab.namespace>: nil p
ointer evaluating interface {}.namespace

I assume xraylab is some unintended leftover?

**Comment by day0hero** [comment]
Reviewed by @ipbabble and applied changes recommended by @mbaldessari

**Pull request merged**
